#[derive(Debug, PartialEq)]
pub enum TournamentError {
    NotImplemented,
    NoParticipants,
    NonExistentParticipant,
    RaceIsFull,
    RacerAlreadyInRace,
    RacerNotInRace,
    InvalidPlacementValue,
    RaceIsNotComplete,
    WrongPhase,
    NotEnoughParticipants,
    PoolsNotCompleted,
    RaceNotFound,
    ResultsDontMatchRace,
    BracketSetAlreadyStarted,
    InvalidBracketSetSize,
    InvalidGroupConfigurations,
    InvalidBracketId,
    BracketNotReady,
}
